### ISSUE TITLE
Update Kutztown University record

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data-venue-us-pa#1]
A continuation of [Issue #360](https://github.com/whosonfirst/whosonfirst-data/issues/360) in the `whosonfirst-data` repo.

Deprecate the [Kutztown University](https://whosonfirst.mapzen.com/spelunker/id/621997697/#11/40.4904/-75.7976) `venue` record and create a new `campus` record. Deprecate both the `locality` and `venue` records to the new campus record.

**Comment by nvkelso** [comment]
LGTM, but needs to be merged at the same time as https://github.com/whosonfirst-data/whosonfirst-data/pull/363.
